module.exports={
    publicPath:'/music',
    devServer:{
        proxy:{
            '/personalized':{
                target:'http://music.eleuu.com',
                changeOrigin:true
            },
        }
    }
}